<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Criar usuario</title>
    </head>
    <body>
        <h3>Criar usuario</h3>
        <span style="color:red"><?php echo $mensagem; ?></span>
        <br />
        <br />
        <form action="index.php?page=salvarusuario" method="POST">
            <span>Numero:</span><input id="numero" name="numero" type="number"/>
            <br />
            <br />
            <input type="submit" value="Salvar"/><a href="listarusuarios.phtml">Cancelar</a>
        </form>
    </body>
</html>
