<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Editar usuario</title>
    </head>
    <body>
        <h3>Editar usuario</h3>
        <form action="listarusuarios.phtml" method="POST">
            <span>Email:</span><input id="email" name="email" type="text"/>
            <br />
            <span>Senha:</span><input id="senha" name="senha" type="password"/>
            <br />
            <span>Confirmar senha:</span><input id="confirmarsenha" name="confirmarsenha" type="password"/>
            <br />
            <br />
            <input type="submit" value="Salvar"/><a href="listarusuarios.phtml">Cancelar</a>
        </form>
    </body>
</html>
