<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Esqueci minha senha</title>
    </head>
    <body>
        <h3>Esqueci minha senha</h3>
        <span style="color:red"><?php echo $mensagem; ?></span>
        <br />
        <br />
        <form action="index.php?acao=esqueciminhasenha" method="POST">
            <span>Email:</span><input id="email" name="email" type="text"/>
            <br />
            <br />
            <input type="submit" value="Enviar"/><a href="login.phtml">Cancelar</a>
        </form>
    </body>
</html>
