<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Listar usuarios</title>
    </head>
    <body>
        <h3>Listar usuarios</h3>
        <table>
            <th>Id</th>
            <th>Email</th>
            <th>Senha</th>
            <th>Acoes</th>
            <tr>
                <td>1</td>
                <td>usuario 1</td>
                <td>senha 1</td>
                <td>
                    <a href="editarusuario.phtml">Editar</a>
                    <a href="listarusuarios.phtml">Deletar</a>
                </td>
            </tr>
            <tr>
                <td>2</td>
                <td>usuario 2</td>
                <td>senha 2</td>
                <td>
                    <a href="editarusuario.phtml">Editar</a>
                    <a href="listarusuarios.phtml">Deletar</a>
                </td>
            </tr>
        </table>
        <br />
        <form action="criarusuario.phtml" method="POST">
            <input type="submit" href="criarusuario.phtml" value="Criar"/>
            <a href="index.phtml">Logout</a>
        </form>
    </body>
</html>