<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Listar usuarios</title>
        <script src="js/scripts.js"></script>
    </head>
    <body>
        <h3>Listar usuarios</h3>
        <table>
            <th>Id</th>
            <th>Email</th>
            <th>Senha</th>
            <th>Acoes</th>
            <?php foreach ($numeros as $n) { ?>
                <tr>
                    <td><?php echo $n; ?></td>
                    <td>usuario <?php echo $n; ?></td>
                    <td>senha <?php echo $n; ?></td>
                    <td>
                        <a href="editarusuario.phtml">Editar</a>
                        <a href="listarusuarios.phtml" onclick="return confirm('Tens certesa?');">Deletar</a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <br />
        <form action="index.php?page=criarusuario" method="POST">
            <input type="submit" value="Criar"/>
            <a href="index.phtml">Logout</a>
        </form>
    </body>
</html>